### ISSUE TITLE
"Cannot find decoder for opcode 1f"

### ISSUE THREAD

**Issue by heegaiximephoomeeghahyaiseekh** [jkinder/jakstab#7]
Tried to analyze /bin/sh on a Debian Jessie machine.

/bin/sh on that machine is the amd64 build of Dash 0.5.7-4+b1.

```
user@linux:/tmp/jakstab$ uname -a
Linux servea 3.16.0-4-amd64 #1 SMP Debian 3.16.36-1+deb8u2 (2016-10-19) x86_64 GNU/Linux
user@linux:/tmp/jakstab$ ./jakstab -m /bin/sh
=======================================================================
   Jakstab 0.8.4-devel
   Copyright 2007-2015  Johannes Kinder  <jk@jakstab.org>

   Jakstab comes with ABSOLUTELY NO WARRANTY. This is free software,
   and you are welcome to redistribute it under certain conditions.
   Refer to LICENSE for details.
=======================================================================
Reading machine specification from pentium.ssl.
Parsing /bin/sh...
Cannot find decoder for opcode 1f.
Exception in thread "main" java.lang.NullPointerException
	at org.jakstab.loader.elf.ELFModule.<init>(ELFModule.java:135)
	at org.jakstab.Program.loadModule(Program.java:145)
	at org.jakstab.Program.loadMainModule(Program.java:116)
	at org.jakstab.Main.main(Main.java:115)

```

**Comment by jkinder** [comment]
Jakstab only supports 32 bit Intel x86. There is no support for analyzing 64 bit executables.
