### ISSUE TITLE
Error While running Jakstab on simple hello world program compiled in Ubuntu 16.04 machine

### ISSUE THREAD

**Issue by bernardnongpoh** [jkinder/jakstab#9]
Exception in thread "main" java.lang.AssertionError
	at org.jakstab.loader.elf.ELFModule.<init>(ELFModule.java:120)
	at org.jakstab.Program.loadModule(Program.java:145)
	at org.jakstab.Program.loadMainModule(Program.java:116)
	at org.jakstab.Main.main(Main.java:115)

**Comment by pythonpsycho1337** [comment]
I encountered the same problem. From my brief study of the code throwing the exception, it seems like the problem occurs because Jakstab assumes that the ELF binary must have a .dynamic and .plt section. However, not all ELF binaries have these section.

**Comment by 1Husin-Alhaj** [comment]
this issue is closed without providing any solution for the given problem!!!

**Comment by jkinder** [comment]
Fair - the problem persists. Feel free to submit a PR fixing it.

**Comment by 1Husin-Alhaj** [comment]
I have faced the same problem and I compiled a very tiny and simple c code file in Ubuntu using multiple ways but I always got the same error:

![image](https://user-images.githubusercontent.com/17450624/96586171-7c7c4480-12ed-11eb-845c-87c9502b2616.png)

I tried to extract CFG for executable file, shared file, and object file ... but none of them worked

**Comment by jkinder** [comment]
@tpetersonkth seems to have pinpointed the issue in his comment above. You can try fixing it following the lead in his comment.

**Comment by tpetersonkth** [comment]
@1Husin-Alhaj The version of Jakstab I used is available here: https://github.com/tpetersonkth/AlternatingControlFlowReconstruction/ in the Jakstab folder. This version is not much different from Kinder's version except that it adds under-approximation possibilities through extra command line options. I think the only fixes I did for this issue was to comment out some code in the ELFModule file. I am pretty sure that I did not do a proper fix though, that's why I didn't try to patch the official project. The changes made it work for binaries which didn't contain the missing sections mentioned in the error message. 

You can try to see my changes in the ELFModule file or you can try to run the modified jakstab version I linked on your binaries directly. I think it should work.

**Comment by 1Husin-Alhaj** [comment]
[SoK: All You Ever Wanted to Know About x86/x64 Binary Disassembly But Were Afraid to Ask](https://oaklandsok.github.io/papers/pang2021.pdf)
![image](https://user-images.githubusercontent.com/17450624/98156109-93758600-1eec-11eb-8275-36b89d75d94c.png)
